/**
 * Helper to dynamically import the wasm-pack generated module.
 * Uses eval to completely bypass TypeScript module resolution.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function importWasmModule(): Promise<any> {
  // Using eval to bypass TypeScript's static module resolution
  // The actual module is generated by wasm-pack at build time
  // eslint-disable-next-line no-eval
  return eval('import("./pkg/delta_ltsc_core.js")');
}
